### ISSUE TITLE
What about vim, zsh, bash, ls, grep, dircolors, tmux, etc?

### ISSUE THREAD

**Issue by ghost** [mbadolato/iTerm2-Color-Schemes#245]
It would be absolutely cool to extend this project to many Linux tools and create something like the Dracula project (https://draculatheme.com) but for iTerm2 themes.

**Comment by tehaleph** [comment]
@mbadolato how do you feel about refactoring conversion tools? 

Now it is a set of scripts in different languages (most of which just translate data from xrdb to different templates) but I think we can rewrite this into a single utility that will use some kind of template engine. 

Yes, this is less Unix-way than a set of separate scripts for each case but I sure it will be easier to expand – instead of copying and changing scripts, you will only need to add a new template.

If you don't mind this I'm ready to do it.

**Comment by mbadolato** [comment]
Absolutely! I'd welcome any improvements/changes! Pretty much I just started collecting themes and it's grown and people have submitted various tools over there years etc. There's really been no design or thought to cohesiveness; I've just accepted what people send over because it's always been helpful to have!

**Comment by tehaleph** [comment]
Cool! I think I can do it this weekend.

**Comment by Toontje** [comment]
> Cool! I think I can do it this weekend.

NICE! I wish i could help, but my programming skills are close to zero. Working on it though. ;-)
