### ISSUE TITLE
README Cleanup

### ISSUE THREAD

**Issue by jdhmtl** [mbadolato/iTerm2-Color-Schemes#339]
Currently, the screenshots are being referenced in three places -- the main `README`, `screenshots/README`, and the `gh-pages` branch. This leads to both duplication and inconsistency. Leaving aside the GitHub Pages issue for the moment, what are your thoughts on removing screenshots from the README and instead linking from that file to `screenshots/README`, which can easily be updated programmatically?

Additionally, what are your thoughts about the creation of a dedicated credits file, also linked to from the README, rather than having a block of text beneath the images in the main README? Could substantially cut down on the length of the README while still retaining all the content.

**Comment by mbadolato** [comment]
A linked credits file instead of the main README would be fine, and quite useful.

For the screenshots, I prefer to keep them in the README so that they show up on the main GH page when someone views it, though I guess a prominent link at the very top would alleviate that I guess. But, I also think that having the names with the screenshots on the main page is better for SEO, though that's just a guess. Thoughts?

**Comment by jdhmtl** [comment]
That's fair. I hadn't really considered SEO, and I don't know a ton about how that works under the hood. Happy to make the credits changes, though.

**Comment by jdhmtl** [comment]
Closed by #343
