### ISSUE TITLE
Ayu Mirage Theme Error

### ISSUE THREAD

**Issue by Confucian-e** [mbadolato/iTerm2-Color-Schemes#378]
It shows 404 when I open [Ayu Mirage](https://raw.githubusercontent.com/mbadolato/iTerm2-Color-Schemes/master/schemes/Ayu+Mirage.itermcolors)
how can I download Ayu Mirage theme?

**Comment by pcolladosoto** [comment]
Hi @Confucian-e! The link seems to be down at the moment... You can nevertheless download the theme over at:

https://raw.githubusercontent.com/mbadolato/iTerm2-Color-Schemes/master/schemes/Ayu%20Mirage.itermcolors

You can also take a look at the 'rendered' file over [here](https://github.com/mbadolato/iTerm2-Color-Schemes/blob/master/schemes/Ayu%20Mirage.itermcolors).

In any case, it looks like the link on [`index.html`](https://github.com/mbadolato/iTerm2-Color-Schemes/blob/gh-pages/index.html#L224) is not quite right: it looks like the space should be escaped with `%20` instead of being represented with a `+` sign.

I'll open a PR right away to see if that solves the issue...

**Comment by Confucian-e** [comment]
Thank you guy!
