### ISSUE TITLE
xfce4terminal schemes outputs to wrong folder

### ISSUE THREAD

**Issue by alexeyten** [mbadolato/iTerm2-Color-Schemes#383]
New `tools/gen.py` outputs xfce4terminal files into folder `xfce4termnal/` instead of 
`xfce4terminal/colorschemes/`

Is it intentional or just a bug?

**Comment by tehaleph** [comment]
Basically yes, it's a bug because I didn't make a way to use sub-folders in the new templates flow.

Judging by the documentation from xfce4-terminal, the sub-folder was made simply for the convenience of copying all themes into the terminal settings.

/cc @mbadolato @jdhmtl 
Do we want to support this feature and make it possible to describe custom output path in templates. Or we can just regenerate themes for xfce4-terminal without a sub-folder?

**Comment by mbadolato** [comment]
@tehaleph I'm all for either way, however, I lean more towards without subfolder. If the custom path isn't required, no need to add another layer
